<h1><?= $dataset->title ?></h1>
<div class="container">
    <div class="row">
        <div class="col-md-3">
            <?= $this->partial('mkdf/datasets/partial/dataset-features', ['features' => $features, 'dataset_id' => $dataset->id] ) ?>
        </div>
        <div class="col-md-9">
            <h2>Stream details</h2>
            <?= $this->partial('mkdf/core/partial/actions', $actions); ?>
            <!--
            UUID: <?= $dataset->uuid ?><br />
            -->

            <?php if($stream_exists): ?>
                <?= $this->partial('mkdf/stream/partial/stream-active', ['stream_url' => $stream_url, 'doc_count' => $doc_count, 'dataset' => $dataset] ) ?>
            <?php endif; ?>

            <?php if(!$stream_exists): ?>
                <?= $this->partial('mkdf/stream/partial/stream-inactive', ['dataset' => $dataset, 'keys' => $keys, 'can_edit' => $can_edit] ) ?>
            <?php endif; ?>
        </div>
    </div>
</div>