<h1>Remove key access</h1>
<?= $this->partial('mkdf/core/partial/messages', ['messages' => $messages] ) ?>
<!-- Token: <?= $token ?> -->
<p><em>Note that the access key itself will not be deleted. Access to other datasets with this key will not be affected.</em></p>
<?= $this->partial('mkdf/core/partial/actions', [
    'buttons'=>[
        ['type'=>'danger','label'=>'Yes, remove this key\'s access', 'target'=> 'stream', 'params'=> ['id' => $dataset->id, 'action' => 'removekey'], 'query' => ['token' => $token, 'key' => $key]],
        ['type'=>'secondary','label'=>'No, go back please', 'target'=> 'stream', 'params'=> ['id' => $dataset->id, 'action' => 'details']]]
] ); ?>