<h1><?= $dataset->title ?> - JSON Browser</h1>
<div class="container">
    <div class="row">
        <div class="col-md-3">
            <?= $this->partial('mkdf/datasets/partial/dataset-features', ['features' => $features, 'dataset_id' => $dataset->id] ) ?>
        </div>
        <div class="col-md-9">
            Controller content here<br>
            Doc count: <?= $doc_count ?>
        </div>
    </div>
</div>