<div class="card">
    <div class="card-body">
        <h5 class="card-title"><!--Stream-->API active</h5>
        <h6 class="card-subtitle mb-2 text-muted">This <!--Stream--> API is active and ready for read/write operations</h6>
        <p class="card-text">

        <table class="table table-bordered">
            <tr>
                <th>UUID:</th>
                <td><?= $this->escapeHtml($dataset->uuid) ?></th>
            </tr>
            <?php if ($can_read && $user_has_key): ?>
                <tr>
                    <th>READ:</th>
                    <td><div style="font-size: 0.85em;"><?= $this->escapeHtml($read_url) ?></div></th>
                </tr>
                <tr>
                    <th>BROWSE:</th>
                    <td><div style="font-size: 0.85em;"><?= $this->escapeHtml($browse_url) ?></div></th>
                </tr>
                <tr>
                    <th>API Explorer:</th>
                    <td><div style="font-size: 0.85em;"><a href="<?= $this->escapeHtml($api_home) ?>" target="_blank"><?= $this->escapeHtml($api_home) ?></a></div></th>
                </tr>
            <?php endif; ?>
            <tr>
                <th>Total docs:</th>
                <td><?= $this->escapeHtml($doc_count) ?></td>
            </tr>
        </table>

        <?php

            if ($user_has_key) {
                print('<h5>Your keys on this dataset</h5>');
                print ('<table class="table table-bordered">');
                print ('<tr><th>UUID / Description</th> <th>Permission</th> <th>Actions</th></tr>');
                foreach ($userDatasetKeys as $key) {
                    $permissionLabel = '';
                    switch ($key['permission']) {
                        case 'a':
                            $permissionLabel = 'read/write';
                            break;
                        case 'r':
                            $permissionLabel = 'read';
                            break;
                        case 'w':
                            $permissionLabel = 'write';
                            break;
                        case 'd':
                            $permissionLabel = 'disabled';
                            break;
                        default:
                            $permissionLabel = 'unknown';
                    }
                    if ($key['permission'] == 'd') {
                        print ('<tr class="table-secondary">');
                    }
                    else {
                        print ('<tr>');
                    }
                    print ('<td><em>'.$key['keyUUID'].'</em><br />'.$key['keyName'].'</td> <td><em>'.$permissionLabel.'</em></td>');
                    print ('<td>');
                    $deleteAction = [
                        'class'=>'btn-group-sm',
                        'buttons'=>[
                            ['type'=>'primary','label'=>'Remove', 'icon' => 'delete', 'target'=> 'stream', 'params'=> ['id' => $dataset->id, 'action' => 'removekey'], 'query' => ['key' => $key['keyUUID']]],
                        ]
                    ];
                    print($this->partial('mkdf/core/partial/actions', $deleteAction));
                    print ('</td></tr>');

                }
                print ('</table>');
                $actions['buttons'][] = [
                    'type' => 'primary',
                    'label' => 'Register another key',
                    'icon' => 'bookmark',
                    'target' => 'stream',
                    'params' => [
                        'action' => 'subscribe',
                        'id' => $dataset->id
                    ]
                ];
            }
        ?>
        <?php if($can_read || $can_write): ?>
            <?= $this->partial('mkdf/core/partial/actions', $actions); ?>
        <?php endif; ?>

        </p>

    </div>
</div>


